<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle(( $pagetitle )); ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <link rel="stylesheet" type="text/less" href="/css/style.less" media="screen, projection" />
    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon','href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.less');
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()

        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/less-1.5.0.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')

        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))

    ; ?>

</head>
<body>
<div class="header">
    <p>Test project</p>
</div>


<div class="nav">
    <a href="<?php echo $this->url('home',array('action'=>'show'));?>">Egfjhdit</a>

</div>

<div class="container">
    <?php echo $this->content; ?>

</div>
<?php echo $this->inlineScript() ?>
</body>
</html>
